"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _product_detail from './product-detail.bones.json'
import _conversation_list from './conversation-list.bones.json'
import _chat_messages from './chat-messages.bones.json'
import _product_grid from './product-grid.bones.json'
import _profile from './profile.bones.json'

registerBones({
  "product-detail": _product_detail,
  "conversation-list": _conversation_list,
  "chat-messages": _chat_messages,
  "product-grid": _product_grid,
  "profile": _profile,
})
